services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017


  application:
    image: "node:18"
    user: "node"
    working_dir: /home/app
    environment:
      - DB_HOST=mongo 
      - PORT=80
    volumes:
      - ./app/:/home/app
    ports:
      - "80:80"  
    command: "npm start"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 15s
      timeout: 10s
      retries: 10

